### ISSUE TITLE
İşlemlerin Çalışmaması

### ISSUE THREAD

**Issue by blackshougun** [abdullahcicekli/instagrambot#1]
Merhaba, botu çalıştırdığımda chromedriver ı açıyor, ve tanımladığım hesaba giriş yapıyor, ancak menüden seçtiğim işlemleri gerçekleştirmiyor, örneğin ilk olarak kendi takipçi listemi seçmeye çalıştığımda şu şekilde hata veriyor:
![resim](https://user-images.githubusercontent.com/55887078/85760037-2110c000-b71a-11ea-8de7-1d948e28c33f.png)
Belirtilen kütüphaneleri kurdum, sorun nerede olabilir ?

**Comment by abdullahcicekli** [comment]
Merhaba. Chrome hesaba giriş yaptıktan sonraki aşamayı gözlemleyin. Eğer internetinizde bir yavaşlık sözkonusu ise (chromedriver da bunu yapabilir) sayfa tam yüklenmeden profilinize girmeye çalışıyorsa hata almanız mümkün olabilir. Bu durumu gözlemleyin. Eğer böyle birşey var ise 29. satırdaki time.sleep(2) nin değerini arttırmayı deneyin ve tekrar gözlemleyin. Eğer giriş yaptıktan sonra profilinizi açıyorsa ve hata o aşamada gerçekşiyorsa yine sayfanın tam yüklendiğinden emin olun. Eğer sayfa yüklenmesi tamamlandıktan sonra hata alıyorsanız 200. satırdaki 
self.browser.find_element_by_xpath("//*[@id='react-root']/section/main/div/header/section/ul/li[2]/a").click()
satırının ("//*[@id='react-root']/section/main/div/header/section/ul/li[2]/a") kısmındaki tırnaklar içerisindeki kısmı kendi profiline göre ayarlamanız gerekbilir. İnstagram bazen yaptığı değişiklerle botları kullanılamaz hale getirebiliyor. Bu işlemi gerçekleştirmek için profilinizin olduğu web sayfaya sağ tıklayıp incele dedikten sonra takipçiler yazan kısma bir daha sağ tıklayıp incele diyeceksiniz. Gösterilen elment renkli olarak yanıp söner. Kaynak kodundaki o satıra sağ tıklayıp copy xpath ile dizininiz bahsettiğim tırnak içlerine yapıştırıp sorunu çözöebilirsiniz.

**Comment by abdullahcicekli** [comment]
timeout.
